#ifndef GIT_VERSION_H
#define GIT_VERSION_H

// This file is automatically generated during build
// Do not edit manually

#ifndef GIT_BRANCH
#define GIT_BRANCH "unknown"
#endif

#ifndef GIT_COMMIT_HASH
#define GIT_COMMIT_HASH "unknown"
#endif

#ifndef GIT_COMMIT_DATE
#define GIT_COMMIT_DATE "unknown"
#endif

#ifndef GIT_VERSION
#define GIT_VERSION "unknown"
#endif

#ifndef GIT_DIRTY_FLAG
#define GIT_DIRTY_FLAG ""
#endif

// Build timestamp
#define BUILD_DATE __DATE__
#define BUILD_TIME __TIME__

// Helper function to check if build is clean
static inline bool is_clean_build(void) {
    return (GIT_DIRTY_FLAG[0] == '\0');
}

#endif // GIT_VERSION_H